chore(playwright): new reporter options for Allure TestOps compatibility
allure-framework/allure-js pull request #448
Opened 2022-06-01 07:16 UTC by serembon

### Context

#### Checklist
- [ ] [Sign Allure CLA][cla]
- [ ] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

2022-06-01 07:49 UTC, baev requested changes
please revert all the formatting changes

2022-06-01 07:49 UTC, baev commented on packages/allure-playwright/README.md
> +| suiteTitle   | Use test tittle instead of test file path in report | `false`            |
typo

2022-06-01 07:49 UTC, baev commented on packages/allure-playwright/README.md
> +| suiteTitle   | Use test tittle instead of test file path in report | `false`            |
BTW the description is unclear

2022-06-01 11:45 UTC, serembon commented on packages/allure-playwright/README.md
> +| suiteTitle   | Use test tittle instead of test file path in report | `false`            |
Done

2022-06-02 08:06 UTC, baev approved these changes
Looks good!

2022-06-02 08:09 UTC, baev commented
BTW I rather introduce bunch of new labels instead of changing the default one. Allure TestOps provides an options to change the grouping and use any other label (mapped to custom field). But it's much harder to change the behaviour for Allure Report users

2022-06-21 14:56 UTC, merged