Add auto-detect of attachments extension  [playwright]
allure-framework/allure-js pull request #470
Opened 2022-07-27 14:18 UTC by elipskiy

The Playwright Reporter missed attachments whose extensions could not detect from content type. 

Add auto detect file extensions from the file name. 

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

2022-07-27 14:22 UTC, baev requested changes

2022-07-27 14:22 UTC, baev commented on packages/allure-js-commons/src/AllureRuntime.ts
> +    fromPath: string,
breaking change, please revert

2022-07-28 12:15 UTC, elipskiy commented on packages/allure-js-commons/src/AllureRuntime.ts
> +    fromPath: string,
fixed

2022-08-09 13:33 UTC, vovsemenv commented
@elipskiy some tests are failed. Could you fix it?

2022-08-15 08:15 UTC, vovsemenv approved these changes

2022-08-16 08:20 UTC, vovsemenv commented
@baev we ready to go

2022-09-30 10:08 UTC, elipskiy commented
@baev please, merge this pr

2022-10-18 12:03 UTC, elipskiy commented
@baev @viclovsky

2022-10-18 12:29 UTC, baev commented
The PR isn't merged yet due to the following concerns:

1. Attachment file extension isn't really necessary as it will be detected automatically during report generation if correct content type is supplied. 
2. Besides that, we can use file content to detect correct content type (by using magic bytes) -- it's already implemented in both Allure Report & Allure TestOps
3. It makes sense to reuse existing file extension though. But I'm not sure about extname -- there are plenty of complex file extensions like `tar.gz` , and it may be confusing for some users (or not)
4. Why playwright? The main change is located in commons, so you need to add test to commons module.

2024-05-21 11:45 UTC, baev commented
fixed via https://github.com/allure-framework/allure-js/pull/956

2024-05-21 11:45 UTC, closed without merging