chore(build): Switch from yarn to npm
allure-framework/allure-js pull request #562
Opened 2022-12-27 08:30 UTC by vovsemenv

Sucessor of https://github.com/allure-framework/allure-js/pull/471 with fixed versions in publish workflow

2022-12-27 12:07 UTC, vovsemenv commented
I tested releasy cycle here https://github.com/vovsemenv/allure-js
version updates works fine

2023-01-04 06:40 UTC, baev requested changes
- [ ] Ensure package contents (attach the contents of tarballs to the PR)
- [ ] Ensure package versions are correct when run `npm pack`
- [ ] Add instructions on how to add a new package
- [ ] Add instructions on how to work with this workspace setup (how to build, how to test changes in commons module, etc)

2023-01-04 06:40 UTC, baev commented on .github/workflows/build.yml
> -      - uses: actions/checkout@v3.1.0
why downgrade

2023-01-04 06:40 UTC, baev commented on .github/workflows/build.yml
> -        uses: actions/setup-node@v3
why downgrade

2023-01-04 06:40 UTC, baev commented on packages/allure-jest/package.json
> +    "test": "rimraf ./out; npm run jasmineTest"
use preTest instead

2023-01-04 06:40 UTC, baev commented on packages/allure-jasmine/package.json
> +    "test": "rimraf ./out ; npm run runTest ; npm run generate-report"
use preTest instead

2023-01-04 06:40 UTC, baev commented on update-local-deps.mjs
> +import { readFile, writeFile } from "node:fs/promises";
Maybe use relative package links and add a pre-package script that replaces relative versions with the correct ones?

2023-03-27 06:21 UTC, closed without merging