feature(playwright): Add selective launch for playwright
allure-framework/allure-js pull request #605
Opened 2023-02-03 15:50 UTC by vovsemenv

### TestPlan usage

```diff
+ import { testPlanFilter } from "allure-playwright/dist/testplan";
export default {
  reporter: [
    [
      "allure-playwright",
    ],
  ],
  projects: [
    {
      name: "chromium",
    },
  ],
+  grep: testPlanFilter()
};
```

2023-02-05 20:57 UTC, vovsemenv commented
@pavelfeldman  or @mxschmitt please also check this PR and leave you opinion about using grep field for this task.

2023-02-06 15:39 UTC, mxschmitt commented on packages/allure-playwright/package.json
> +    "@types/node": "^16",
@playwright/test already depends on @types/node, so I'd move it to a devDependency instead.

2023-02-07 10:19 UTC, baev requested changes

2023-02-07 10:19 UTC, baev commented on packages/allure-playwright/src/testplan.ts
> +    const testPlanPath = process.env.ALLURE_TESTPLAN_PATH;
move test plan parsing to commons

2023-02-07 11:20 UTC, baev commented on packages/allure-playwright/src/testplan.ts
> +    const testPlanPath = process.env.ALLURE_TESTPLAN_PATH;
@vovsemenv see https://github.com/allure-framework/allure-js/pull/464

2023-02-07 12:30 UTC, epszaw requested changes
✅ The functionality works well, tested locally
✅ The code looks also good
⚠️ Please, pay your attention to my comments about tests

2023-02-07 12:30 UTC, epszaw commented on packages/allure-playwright/test/testplan.spec.ts
> +  expect(results.length).toBe(3);
Could you check what the tests exactly we have there?
Current check is a bit vague and we potentially can have any results, even not matched by filter function.

2023-02-07 12:30 UTC, epszaw commented on packages/allure-playwright/src/testplan.ts
> +export const escapeRegExp = (value: string): string => {
It would be nice, to test utility functions too

2023-02-07 14:16 UTC, epszaw approved these changes
✅ Looks much better! Thank you for the changes!

2023-02-08 04:48 UTC, baev approved these changes

2023-02-08 08:48 UTC, merged