feature(playwright): allow passing metadata from playwright test titles
allure-framework/allure-js pull request #635
Opened 2023-03-09 09:53 UTC by vovsemenv

2023-03-13 07:06 UTC, guiyomh approved these changes

2023-03-13 09:26 UTC, baev requested changes
Can we remove tags from test titles? Besides that, I'd like to have all the tags displayed as tags in the report

2023-03-16 07:22 UTC, vovsemenv commented
fixes https://github.com/allure-framework/allure-js/issues/634

2023-05-03 10:23 UTC, epszaw approved these changes
✅ The feature looks very useful. Guess we can implement the same for rest reporters. Code looks nice. Good job! 👍

2023-05-08 15:15 UTC, baev approved these changes

2023-05-08 15:16 UTC, merged