fix:count in repeatEach so that testcases are distinctive as repeatEach is not the same as retry
allure-framework/allure-js pull request #664
Opened 2023-04-20 15:19 UTC by alyaothman14

### Context

#### Checklist
- [ x] [Sign Allure CLA][cla]
- [ x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

2023-04-21 02:35 UTC, alyaothman14 commented
@baev I would really appreciate if this can be reviewed and released as the results in AllureTestOps is skewed because of this e.g the pipeline will fail but in testops it marks it as passed

2023-04-21 13:35 UTC, baev requested changes
could you please add a test for the change

2023-04-21 13:35 UTC, baev commented on packages/allure-playwright/src/index.ts
> +    const fullName = `${relativeFile}#${nameSuites}${test.title}${repeatEach ? ` (repeat #${test.repeatEachIndex + 1})` : ""}`;
Add it as a test parameter instead

2023-04-21 13:35 UTC, baev commented on packages/allure-playwright/src/index.ts
> +    const fullName = `${relativeFile}#${nameSuites}${test.title}${repeatEach ? ` (repeat #${test.repeatEachIndex + 1})` : ""}`;
```js
if (project?.repeatEach) {
  allureTest.addParameter("Repeation", test.repeatEachIndex + 1);
}
```

2023-04-22 00:40 UTC, alyaothman14 commented on packages/allure-playwright/src/index.ts
> +    const fullName = `${relativeFile}#${nameSuites}${test.title}${repeatEach ? ` (repeat #${test.repeatEachIndex + 1})` : ""}`;
Thanks updated

2023-05-10 19:12 UTC, baev commented
change included to https://github.com/allure-framework/allure-js/pull/676 

Thanks for the contribution!

2023-05-10 19:12 UTC, closed without merging