change skipped tests handling logic
allure-framework/allure-js pull request #758
Opened 2023-08-22 14:11 UTC by epszaw

### Context

fixes #757 

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

2023-08-25 17:18 UTC, baev approved these changes

2023-08-25 17:19 UTC, baev requested changes
please add a test

2023-08-31 15:06 UTC, baev approved these changes

2023-09-04 08:41 UTC, epszaw commented
@baev added the test

2023-09-04 10:59 UTC, merged