[newman-reporter-allure] Fix: Resolved the issue of formatting in JSON response content displaying in Allure reports.
allure-framework/allure-js pull request #808
Opened 2023-11-17 06:59 UTC by win5923

**Context**
When the `Content-Type` of a response body is `application/json`, the formatting should be normal.

**Screenshot**
Postman:
![image](https://github.com/allure-framework/allure-js/assets/56353753/a8cca1fa-0218-4473-9ad4-0db3dbb6956f)
![image](https://github.com/allure-framework/allure-js/assets/56353753/2f411c05-7c85-46ac-8482-118f3ed07893)

Allure report (anonymised for privacy):
![image](https://github.com/allure-framework/allure-js/assets/56353753/f423b33a-beb5-4607-a1b7-8a9512a81b92)

#### Checklist
- [V] [Sign Allure CLA][cla]
- [X] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

2023-11-17 06:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/allure-framework/allure-js?pullRequest=808) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/allure-framework/allure-js?pullRequest=808) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/allure-framework/allure-js?pullRequest=808) it.</sub>

2023-11-23 17:00 UTC, epszaw requested changes
Thank you for the contribution, good job here!
Please, provide unit-tests for the changes to continue with the PR.

2023-11-24 01:50 UTC, win5923 commented
I have completed the changed, and sorry for not being able to provide unit tests. I am unsure about how to proceed with them. 
Thank you very much for your review.

2023-11-29 13:07 UTC, win5923 commented on packages/newman-reporter-allure/src/index.ts
> +      if (contentTypeHeader && contentTypeHeader.toLowerCase().includes('application/json')) {
done!

2023-12-18 17:46 UTC, win5923 commented
@epszaw Is there anything else that needs to be modified?

2023-12-19 16:24 UTC, epszaw commented
@win5923 please, check typescript errors and linters

2023-12-22 01:52 UTC, closed without merging