Mocha parallel fix
allure-framework/allure-js pull request #967
Opened 2024-05-22 08:57 UTC by delatrie

### Context

The PR allows Allure Mocha to be used with Mocha's `--parallel` mode. It does so by hooking into Mocha's `ParallelBuffered` reporter's [`createListeners`](https://github.com/mochajs/mocha/blob/99601da68d59572b6aa931e9416002bcb5b3e19d/lib/nodejs/reporters/parallel-buffered.js#L119) in a worker thread. Not perfect, but, you know, lesser of two evils.

The patch is set up by introducing a new module into the list of modules Mocha requires at runtime (via `Mocha.MochaOptions.require`). The module only affects worker processes.

### Extra changes

#### New ways to pass a writer into the runtime

A writer can now be provided as a string or an object. That makes it easier to pass the config options across process boundaries.

Now, the following ways are supported:

1. An instance (previously, that was the only way).
2. A string containing a well-known class name or the full path to a module.
3. An array of one or more items. The first one must be a well-known class name or the full path to a module, while the rest are the arguments to the constructor the the class.

The list of well-known classes is as follows:

  - `AllureInMemoryAllureWriter` (all environments)
  - `FileSystemAllureWriter` (node.js only)
  - `AllureInMemoryWriter` (node.js only)
  - `MessageAllureWriter` (node.js only)

The module must export either a writer class or an instance.

Currently, only CJS modules are supported. To support ESM modules, an async extension point is required somewhere in `allure-js-commons.` Since that's primarily a mechanism to test Allure integrations, we might not urgently need it.

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure-js

2024-05-22 12:18 UTC, epszaw requested changes
I'm not able to compile the module due the following error:

```shell
λ yarn compile

src/index.ts → dist/index.mjs...
src/setupAllureMochaParallel.ts:3:45 - error TS7016: Could not find a declaration file for module 'mocha/lib/nodejs/reporters/parallel-buffered.js'. '/Users/epszaw/Code/Work/qameta/allure-js/.yarn/cache/mocha-npm-10.3.0-2a85896b70-8b30b3fdb3.zip/node_modules/mocha/lib/nodejs/reporters/parallel-buffered.js' implicitly has an 'any' type.
  If the 'mocha' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mocha'

3 import { default as ParallelBuffered } from "mocha/lib/nodejs/reporters/parallel-buffered.js";
                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/setupAllureMochaParallel.ts:3

ERROR: "compile:types" exited with 2.
```

2024-05-23 08:58 UTC, delatrie commented on packages/allure-mocha/rollup.config.mjs
> -  return [createNodeEntry("src/index.ts")].flat();
It's for Mocha, not end users. We need Mocha to require this file in its workers via `MochaOptions.requires`. That's why we need it to be a separate file, not part of the bundle.

2024-05-23 09:02 UTC, delatrie commented on packages/allure-mocha/src/utils.ts
> +export const resolveParallelModeSetupFile = () => join(__dirname, `setupAllureMochaParallel${extname(__filename)}`);
Mocha, not us, should require it. Once the full path to that file is put in `MochaOptions.requires`, Mocha's workers will require it (similar to if it was provided via the [`--require`](https://mochajs.org/#-require-module-r-module) CLI argument)

2024-05-23 09:11 UTC, delatrie commented on packages/allure-js-commons/src/sdk/utils.ts
> +export type WellKnownWriters = {
Yep, sure. Done.

2024-05-23 09:29 UTC, epszaw approved these changes

2024-05-23 09:34 UTC, merged